/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.grupointegrado.visao;

import br.edu.grupointegrado.controle.ClassMovimentacao;
import br.edu.grupointegrado.controle.ClassOperacao;
import br.edu.grupointegrado.controle.ClassSaque;
import br.edu.grupointegrado.controle.ClassSessao;

/**
 *
 * @author Luan
 */
public class TelaValorSaque extends javax.swing.JFrame {

    ClassSaque saque;
    ClassMovimentacao movimentacao;
    TelaOperacao operacao;
    TelaInicialCaixa inicial;
    TelaFinalizar finalizar;
    TelaOutroValorSaque outroValorSaque;
    private double valor;
    public TelaValorSaque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB20 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jB40 = new javax.swing.JButton();
        jB300 = new javax.swing.JButton();
        jB200 = new javax.swing.JButton();
        jBMenuAnterior = new javax.swing.JButton();
        jBFinalizarOutroValor = new javax.swing.JButton();
        jB100 = new javax.swing.JButton();
        jB50 = new javax.swing.JButton();
        jB400 = new javax.swing.JButton();
        jBOutroValor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Valor do Saque");
        setAlwaysOnTop(true);
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);

        jB20.setBackground(new java.awt.Color(92, 102, 122));
        jB20.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB20.setForeground(new java.awt.Color(255, 255, 255));
        jB20.setText("20,00");
        jB20.setBorder(null);
        jB20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB20ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Selecione o valor do Saque");

        jB40.setBackground(new java.awt.Color(92, 102, 122));
        jB40.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB40.setForeground(new java.awt.Color(255, 255, 255));
        jB40.setText("40,00");
        jB40.setBorder(null);
        jB40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB40ActionPerformed(evt);
            }
        });

        jB300.setBackground(new java.awt.Color(92, 102, 122));
        jB300.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB300.setForeground(new java.awt.Color(255, 255, 255));
        jB300.setText("300,00");
        jB300.setBorder(null);
        jB300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB300ActionPerformed(evt);
            }
        });

        jB200.setBackground(new java.awt.Color(92, 102, 122));
        jB200.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB200.setForeground(new java.awt.Color(255, 255, 255));
        jB200.setText("200,00");
        jB200.setBorder(null);
        jB200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB200ActionPerformed(evt);
            }
        });

        jBMenuAnterior.setBackground(new java.awt.Color(92, 102, 122));
        jBMenuAnterior.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBMenuAnterior.setForeground(new java.awt.Color(255, 255, 255));
        jBMenuAnterior.setText("Menu Anterior");
        jBMenuAnterior.setBorder(null);
        jBMenuAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMenuAnteriorActionPerformed(evt);
            }
        });

        jBFinalizarOutroValor.setBackground(new java.awt.Color(92, 102, 122));
        jBFinalizarOutroValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBFinalizarOutroValor.setForeground(new java.awt.Color(255, 255, 255));
        jBFinalizarOutroValor.setText("Finalizar");
        jBFinalizarOutroValor.setBorder(null);
        jBFinalizarOutroValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarOutroValorActionPerformed(evt);
            }
        });

        jB100.setBackground(new java.awt.Color(92, 102, 122));
        jB100.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB100.setForeground(new java.awt.Color(255, 255, 255));
        jB100.setText("100,00");
        jB100.setBorder(null);
        jB100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB100ActionPerformed(evt);
            }
        });

        jB50.setBackground(new java.awt.Color(92, 102, 122));
        jB50.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB50.setForeground(new java.awt.Color(255, 255, 255));
        jB50.setText("50,00");
        jB50.setBorder(null);
        jB50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB50ActionPerformed(evt);
            }
        });

        jB400.setBackground(new java.awt.Color(92, 102, 122));
        jB400.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jB400.setForeground(new java.awt.Color(255, 255, 255));
        jB400.setText("400,00");
        jB400.setBorder(null);
        jB400.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB400ActionPerformed(evt);
            }
        });

        jBOutroValor.setBackground(new java.awt.Color(92, 102, 122));
        jBOutroValor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jBOutroValor.setForeground(new java.awt.Color(255, 255, 255));
        jBOutroValor.setText("Outro Valor");
        jBOutroValor.setBorder(null);
        jBOutroValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOutroValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jB20, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB40, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBMenuAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB100, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB50, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jB200, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB300, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBFinalizarOutroValor, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jB400, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBOutroValor, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jB20, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jB200, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jB40, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jB300, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jB50, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jB400, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jB100, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jBOutroValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBFinalizarOutroValor, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMenuAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB20ActionPerformed
        setValor(-20);
        inserirSaqueBotao();
    }//GEN-LAST:event_jB20ActionPerformed

    private void jB40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB40ActionPerformed
        setValor(-40);
        inserirSaqueBotao();
    }//GEN-LAST:event_jB40ActionPerformed

    private void jB300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB300ActionPerformed
       setValor(-300);
       inserirSaqueBotao();
    }//GEN-LAST:event_jB300ActionPerformed

    private void jB200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB200ActionPerformed
        setValor(-200);
        inserirSaqueBotao();
    }//GEN-LAST:event_jB200ActionPerformed

    private void jBMenuAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMenuAnteriorActionPerformed
        setVisible(false);
        operacao.setVisible(true);
    }//GEN-LAST:event_jBMenuAnteriorActionPerformed

    private void jBFinalizarOutroValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarOutroValorActionPerformed
        setVisible(false);
        inicial.setVisible(true);
    }//GEN-LAST:event_jBFinalizarOutroValorActionPerformed

    private void jB100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB100ActionPerformed
       setValor(-100);
       inserirSaqueBotao();
    }//GEN-LAST:event_jB100ActionPerformed

    private void jB50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB50ActionPerformed
        setValor(-50);
        inserirSaqueBotao();
    }//GEN-LAST:event_jB50ActionPerformed

    private void jB400ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB400ActionPerformed
       setValor(-400);
       inserirSaqueBotao();
    }//GEN-LAST:event_jB400ActionPerformed

    private void jBOutroValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOutroValorActionPerformed
       outroValorSaque = new TelaOutroValorSaque();
       outroValorSaque.setInicial(inicial);
        outroValorSaque.setSaque(saque);
        outroValorSaque.setFinalizar(finalizar);
        outroValorSaque.setOperacao(operacao);
        setVisible(false);
        outroValorSaque.setVisible(true);
    }//GEN-LAST:event_jBOutroValorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaValorSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaValorSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaValorSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaValorSaque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaValorSaque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB100;
    private javax.swing.JButton jB20;
    private javax.swing.JButton jB200;
    private javax.swing.JButton jB300;
    private javax.swing.JButton jB40;
    private javax.swing.JButton jB400;
    private javax.swing.JButton jB50;
    private javax.swing.JButton jBFinalizarOutroValor;
    private javax.swing.JButton jBMenuAnterior;
    private javax.swing.JButton jBOutroValor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void inserirSaqueBotao(){
        saque.setVlSaque(valor);
        saque.incluirSaque();
    
        ClassOperacao.setCdSaque(saque.getCdSaque());
        
        operacao.operacao.incluirOperacaoSaque();
        movimentacao = new ClassMovimentacao();
        movimentacao.setCdOperacao(operacao.operacao.getCdOperacao());
        movimentacao.setDsMovimentacao("SAQUE");
        movimentacao.setVlMovimentacao(valor);
        movimentacao.inserirMovimentacao(ClassSessao.getConta());
        
        setVisible(false);
        operacao.finalizar.setVisible(true);
    
    }
    
    
    
    public void setSaque(ClassSaque saque) {
        this.saque = saque;
    }

    public void setOperacao(TelaOperacao operacao) {
        this.operacao = operacao;
    }

    public void setInicial(TelaInicialCaixa inicial) {
        this.inicial = inicial;
    }

    public void setFinalizar(TelaFinalizar finalizar) {
        this.finalizar = finalizar;
    }

    public double getValor() {
        return valor;
    }

    public void setValor(double valor) {
        this.valor = valor;
    }
    
}
