--ALTERAÇÕES SQL BRUNO 09-05-2016
DROP TABLE SALDO;

DELETE FROM CONTA_CLIENTE
WHERE CD_CLIENTE IN (1,2,3);

ALTER TABLE CARTAO
DROP CONSTRAINT FK_CONTA_CARTAO;


INSERT INTO CONTA VALUES(1,1,1,100000,50000);
INSERT INTO CONTA VALUES(2,1,1,200000,100000);
INSERT INTO CONTA VALUES(3,1,2,300000,150000);

ALTER TABLE CARTAO
ADD CONSTRAINT FK_CONTA_CARTAO
FOREIGN KEY (CONTA)
REFERENCES CONTA (CD_CONTA);

INSERT INTO CONTA_CLIENTE VALUES(1,1);
INSERT INTO CONTA_CLIENTE VALUES(2,2);
INSERT INTO CONTA_CLIENTE VALUES(3,3);

CREATE TABLE MOV_CONTA(
CD_CONTA NUMBER,
CD_MOV NUMBER,
VL_SALDO NUMBER,
DT_MOV DATE,
CONSTRAINT PK_MOV_CONTA PRIMARY KEY (CD_CONTA,CD_MOV),
CONSTRAINT FK_CONTA_MC FOREIGN KEY (CD_CONTA) REFERENCES CONTA(CD_CONTA),
CONSTRAINT FK_MOV_MC FOREIGN KEY (CD_MOV) REFERENCES MOVIMENTACAO(CD_MOV));

COMMIT;