
ALTER TABLE SAQUE ADD  (
CD_BANCO NUMBER,
CD_AGENCIA NUMBER,
CD_CONTA NUMBER,
constraint FK_CD_SAQUE foreign key(CD_BANCO,CD_AGENCIA,CD_CONTA) references CONTA(CD_CONTA,CD_AGENCIA,CD_BANCO));

ALTER TABLE TRANSFERENCIA DROP CONSTRAINT fk_conta_td;

