/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.grupointegrado.visao;

import br.edu.grupointegrado.controle.ClassMarca;
import br.edu.grupointegrado.controle.ClassModelo;
import br.edu.grupointegrado.ferramentas.PreencherJTableGenerico;
import br.edu.grupointegrado.ferramentas.Rotina;

/**
 *
 * @author BSP
 */
public class VisaoModelo extends javax.swing.JFrame {
    PreencherJTableGenerico preencher = new PreencherJTableGenerico();    
    ClassMarca marca = new ClassMarca();
    ClassModelo modelo = new ClassModelo();
    
    private char situacao = 'A';
    private int [] chave;
    int rotina;
    
    public VisaoModelo() {
        rotina = Rotina.PADRÃO;
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPcadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFcodigo = new javax.swing.JTextField();
        jTFcodMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFdescMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFdescModelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFdata = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCBsituacao = new javax.swing.JComboBox();
        jBexcluir = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jBnobo = new javax.swing.JButton();
        jBcancela = new javax.swing.JButton();
        jBgravar = new javax.swing.JButton();
        jPconsulta = new javax.swing.JPanel();
        jTFconsulta = new javax.swing.JTextField();
        jCBtipoConsulta = new javax.swing.JComboBox();
        jBconsulta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTconsulta = new javax.swing.JTable();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Código");

        jTFcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcodigoActionPerformed(evt);
            }
        });

        jTFcodMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFcodMarcaFocusLost(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Cod. Marca");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Marca");

        jTFdescMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFdescMarcaFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Modelo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Data");

        jTFdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFdataActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Situação");

        jCBsituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo" }));
        jCBsituacao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCBsituacaoFocusLost(evt);
            }
        });

        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBalterar.setText("Alterar");
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jBnobo.setText("Novo");
        jBnobo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnoboActionPerformed(evt);
            }
        });

        jBcancela.setText("Cancela");
        jBcancela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelaActionPerformed(evt);
            }
        });

        jBgravar.setText("Gravar");
        jBgravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPcadastroLayout = new javax.swing.GroupLayout(jPcadastro);
        jPcadastro.setLayout(jPcadastroLayout);
        jPcadastroLayout.setHorizontalGroup(
            jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcadastroLayout.createSequentialGroup()
                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPcadastroLayout.createSequentialGroup()
                        .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPcadastroLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(jPcadastroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPcadastroLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPcadastroLayout.createSequentialGroup()
                                    .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTFcodigo)
                                        .addComponent(jTFcodMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                                    .addGap(39, 39, 39)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTFdescMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTFdescModelo))
                            .addGroup(jPcadastroLayout.createSequentialGroup()
                                .addComponent(jTFdata, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBsituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPcadastroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBnobo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBgravar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBcancela, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPcadastroLayout.setVerticalGroup(
            jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPcadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTFcodMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTFdescMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFdescModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jCBsituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addGroup(jPcadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnobo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcancela, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBgravar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastro", jPcadastro);

        jCBtipoConsulta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Código", "Modelo", "Marca" }));
        jCBtipoConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBtipoConsultaActionPerformed(evt);
            }
        });

        jBconsulta.setText("Consulta");
        jBconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBconsultaActionPerformed(evt);
            }
        });

        jTconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cód.", "Marca", "Modelo", "Estado", "Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTconsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTconsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTconsulta);
        if (jTconsulta.getColumnModel().getColumnCount() > 0) {
            jTconsulta.getColumnModel().getColumn(0).setResizable(false);
            jTconsulta.getColumnModel().getColumn(0).setPreferredWidth(5);
            jTconsulta.getColumnModel().getColumn(1).setResizable(false);
            jTconsulta.getColumnModel().getColumn(1).setPreferredWidth(15);
            jTconsulta.getColumnModel().getColumn(2).setResizable(false);
            jTconsulta.getColumnModel().getColumn(2).setPreferredWidth(15);
            jTconsulta.getColumnModel().getColumn(3).setResizable(false);
            jTconsulta.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTconsulta.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        javax.swing.GroupLayout jPconsultaLayout = new javax.swing.GroupLayout(jPconsulta);
        jPconsulta.setLayout(jPconsultaLayout);
        jPconsultaLayout.setHorizontalGroup(
            jPconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPconsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPconsultaLayout.createSequentialGroup()
                        .addComponent(jCBtipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jTFconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBconsulta)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPconsultaLayout.setVerticalGroup(
            jPconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPconsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBtipoConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBconsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consulta", jPconsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        setSize(new java.awt.Dimension(434, 394));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFdataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFdataActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBalterarActionPerformed

    private void jBnoboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnoboActionPerformed
     rotina = Rotina.INCLUIR;
    }//GEN-LAST:event_jBnoboActionPerformed

    private void jBcancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelaActionPerformed
        rotina = Rotina.PADRÃO;
        limpajTF();
    }//GEN-LAST:event_jBcancelaActionPerformed

    private void jBgravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgravarActionPerformed
        
        switch(rotina){
            case (Rotina.INCLUIR):
                modelo.setAtivoModelo(situacao);
                modelo.setDataModelo(jTFdata.getText());
                modelo.setMarcaFk(Integer.parseInt(jTFcodMarca.getText()));
                modelo.incluirModelo();
            break;
            case (Rotina.ALTERAR):
                modelo.setAtivoModelo(situacao);
                modelo.setDataModelo(jTFdata.getText());
                modelo.setDescModelo(jTFdescModelo.getText());
                modelo.setMarcaFk(Integer.parseInt(jTFcodMarca.getText()));
                modelo.alterarModelo();
            break;
            
        }
        
        
    }//GEN-LAST:event_jBgravarActionPerformed

    private void jBconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBconsultaActionPerformed
       //Geral, Código, Modelo, Marca
        switch(jCBtipoConsulta.getSelectedIndex()){
            case 0 :
                preencher.PreencherJtableGenerico(jTconsulta,modelo.consultageral());
                break;
            case 1:
                modelo.setCodModelo(Integer.parseInt(jTFconsulta.getText()));
                preencher.PreencherJtableGenerico(jTconsulta, modelo.consultaCod());
                break;
            case 2:
                modelo.setDescModelo(jTFconsulta.getText());
                preencher.PreencherJtableGenerico(jTconsulta,modelo.consultaDescricao());
                break;
            
            case 3:
                preencher.PreencherJtableGenerico(jTconsulta, modelo.consultaDSMarca(jTFconsulta.getText()));
                break;
        
        
        }        
        
    }//GEN-LAST:event_jBconsultaActionPerformed

    private void jCBtipoConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBtipoConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBtipoConsultaActionPerformed

    private void jTconsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTconsultaMouseClicked
        
        if (evt.getClickCount() == 2){
        String x = (String) jTconsulta.getValueAt(jTconsulta.getSelectedRow(), 0);
        modelo.setCodModelo(Integer.parseInt(x));
        modelo.retornaModelo();
        marca.setCodMarca(modelo.getMarcaFk());
        marca.retornaMarca();
         retornadados();
        jTabbedPane1.setSelectedIndex(0);
        rotina = Rotina.ALTERAR;
                }
        
        
    }//GEN-LAST:event_jTconsultaMouseClicked

    private void jTFcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcodigoActionPerformed

    private void jCBsituacaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCBsituacaoFocusLost
     if(jCBsituacao.getSelectedIndex() == 1){
         situacao = 'I';
     }else situacao ='A';
    }//GEN-LAST:event_jCBsituacaoFocusLost

    private void jTFdescMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFdescMarcaFocusLost
        marca.setDescMarca(jTFdescMarca.getText());
        marca.retornaMarcaDesc();
        jTFcodMarca.setText(""+marca.getCodMarca()+"");
    }//GEN-LAST:event_jTFdescMarcaFocusLost

    private void jTFcodMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFcodMarcaFocusLost
        marca.setCodMarca(Integer.parseInt(jTFcodMarca.getText()));
        marca.retornaMarca();
        jTFdescMarca.setText(marca.getDescMarca());
    }//GEN-LAST:event_jTFcodMarcaFocusLost

    /**.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoModelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoModelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBcancela;
    private javax.swing.JButton jBconsulta;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBgravar;
    private javax.swing.JButton jBnobo;
    private javax.swing.JComboBox jCBsituacao;
    private javax.swing.JComboBox jCBtipoConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPanel jPcadastro;
    private javax.swing.JPanel jPconsulta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFcodMarca;
    private javax.swing.JTextField jTFcodigo;
    private javax.swing.JTextField jTFconsulta;
    private javax.swing.JTextField jTFdata;
    private javax.swing.JTextField jTFdescMarca;
    private javax.swing.JTextField jTFdescModelo;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTconsulta;
    // End of variables declaration//GEN-END:variables

    
    public void limpajTF(){
    jTFcodigo.setText("");
    jTFcodMarca.setText("");
    jTFdescMarca.setText("");
    jTFdescModelo.setText("");
    jTFdata.setText("");
    }
    
    
    public void retornadados(){
    jTFcodigo.setText(Integer.toString(modelo.getCodModelo()));
    jTFcodMarca.setText(Integer.toString(modelo.getMarcaFk()));
    jTFdescMarca.setText(marca.getDescMarca().toString());
    jTFdescModelo.setText(modelo.getDescModelo().toString());
    jTFdata.setText(modelo.getDataModelo().toString());
    jCBsituacao.setSelectedIndex(indexjCBsituacao());
}

    private int indexjCBsituacao(){
        situacao = modelo.getAtivoModelo();
        
        if (situacao == 'A'){
            return 0;}
        else
            return 1;
    
    
    }
    
}

